apiVersion: v1
name: grafana
version: 3.3.4
appVersion: 7.1.2
description: Grafana is an open source, feature rich metrics dashboard and graph editor for Graphite, Elasticsearch, OpenTSDB, Prometheus and InfluxDB.
keywords:
  - analytics
  - monitoring
  - metrics
  - logs
home: https://grafana.com/
sources:
  - https://github.com/bitnami/bitnami-docker-grafana
maintainers:
  - name: Bitnami
    email: containers@bitnami.com
engine: gotpl
icon: https://bitnami.com/assets/stacks/grafana/img/grafana-stack-220x234.png
annotations:
  category: Analytics
