# Default values for flink.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## flink image
image: pfisterb/flink:1.12.1
imagePullPolicy: IfNotPresent

## The cluster-id is used for identifying a unique Flink cluster.
## The id must only contain lowercase alphanumeric characters and "-".
clusterid: "flink-native"

## configure the NodePort for external access
## will be configured automatically if left empty
nodePort: 30881 

jobmanager:
  ## The user-specified annotations that are set to the JobManager pod.
  ## The value could be in the form of a1:v1,a2:v2
  annotations: "prometheus.io/scrape:true,prometheus.io/port:9999"

  ## The labels to be set for JobManager pod. Specified as key:value pairs separated by commas.
  ## For example, version:alphav1,deploy:test.
  labels: "component:jobmanager"

taskmanager:
  ## The user-specified annotations that are set to the JobManager pod.
  ## The value could be in the form of a1:v1,a2:v2
  annotations: "prometheus.io/scrape:true,prometheus.io/port:9999"

  ## The labels to be set for JobManager pod. Specified as key:value pairs separated by commas.
  ## For example, version:alphav1,deploy:test.
  labels: "component:taskmanager"


## High availability configurations
highAvailability:
  enabled: false

  ## Must be a durable file system that is accessible from all nodes
  ## (like HDFS, S3, Ceph, nfs, ...)
  storageDir: hdfs:///flink/ha
